# Header

menu:
  主页: /
  编程技术: /tags/编程/
  运维拓展: /tags/运维/
  数据库知识: /tags/数据库/
  docker记录: /tags/docker/
  # 建站技术: /tags/建站/
  # rabbitmq: /tags/rabbitmq/
  树莓派学习: /tags/树莓派/
  软路由探索: /tags/软路由/
  闲谈娱乐: /tags/闲谈/

# SubNav
subnav:
  github: "https://github.com/xiajunyi"
  #weibo: "#"
  rss: /rss.xml
  #zhihu: "#"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  mail: "xjyaction@163.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '打赏看心情，只愿有帮助'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /img/xjy/alipay.jpg
# 微信二维码图片地址
weixin: /img/xjy/wxpay.png

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: false
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: /img/xjy/monkey.jpg

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: true

#2、网易云跟帖
wangyiyun: true

#3、畅言
changyan: false
changyan_appid: cytCkNokt
changyan_conf: prod_d15f92d288a4dbf0e9ddf361b4f87fda

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
cusdis: true
cusdis_host: https://cusdis.xiajunyi.com
cusdis_appid: 4d0c5b2e-e507-46da-abae-7233242d7bb2
disqus: false

#5、Gitment
gitment_owner: false      #你的 GitHub ID
gitment_repo: ''          #存储评论的 repo
gitment_oauth:
  client_id: ''           #client ID
  client_secret: ''       #client secret

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于我'

#友链
friends:
  xiajunyi的wordpress: https://blog.xiajunyi.com/
  tiger的博客: https://www.abstiger.com/
  reallinxu的博客: https://www.reallinxu.com/
  dkvirus的博客: http://blog.dkvirus.com/
  wangyazheng的博客: http://www.wangyazheng.com
  xbzhang的博客: http://blog.xbzhang.com/
  team19的博客: https://team19.abstiger.com/
  夏日的风的博客: https://yuangaopeng.com/
  

#关于我
aboutme: <center>我是一个不甘平庸的码农，我相信知识改变命运，努力带来成功！</center>

#声明
declare_type: 1
licensee_author: 夏军谊
licensee_url: https://creativecommons.org/licenses/by-nc-sa/4.0/
licensee_name: '知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议'

#背景音乐
background_music:
 enable: true
 src: "/music/人生何处不相逢.mp3"
